model:
  neurons: 64
  layers: 8
  hidden_size: 64
  steps_to_stop: 20
  learning_rate: 0.00001
  batch_size: 20

graphs:
  tasks: 10
  dags: 1
  cores: 2
  edge: 15
  levels: 2

amount: 5

file: "graphs/100graphs-c2-t50.pkl"
