model:
  neurons: 128
  layers: 16
  hidden_size: 128
  steps_to_stop: 5
  learning_rate: 0.00001
  batch_size: 1

graphs:
  tasks: 10
  dags: 1
  cores: 2
  edge: 15
  levels: 2

amount: 5

file: "graphs/uav.pkl"
