model:
  neurons: 32
  layers: 8
  hidden_size: 32
  steps_to_stop: 10
  learning_rate: 0.0002
  batch_size: 1

graphs:
  tasks: 10
  dags: 1
  cores: 2
  edge: 15
  levels: 2

amount: 5

file: "graphs/1graphs-c2-t50.pkl"
