model:
  neurons: 16
  layers: 4
  hidden_size: 16
  steps_to_stop: 20
  learning_rate: 1e-3
  batch_size: 3

graphs:
  tasks: 50
  dags: 1
  cores: 2
  edge: 15

training_set: 30

jobs: 10

single: True